# Generated by Django 5.0.3 on 2024-03-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="family",
        ),
        migrations.AddField(
            model_name="genus",
            name="family",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genera",
                to="plants.family",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="species",
                to="plants.genus",
            ),
            preserve_default=False,
        ),
    ]
