# Generated by Django 5.0.3 on 2024-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0002_remove_species_family_genus_family_species_genus"),
    ]

    operations = [
        migrations.AddField(
            model_name="cultivar",
            name="latin_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genus",
            name="latin_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
